// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 2:11:43 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/_4_Work/Web/torrent-nuxt/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/plugins/**/*.{js,ts,mjs}","D:/_4_Work/Web/torrent-nuxt/frontend/composables/**/*.{js,ts,mjs}","D:/_4_Work/Web/torrent-nuxt/frontend/utils/**/*.{js,ts,mjs}","D:/_4_Work/Web/torrent-nuxt/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/_4_Work/Web/torrent-nuxt/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;