// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/10/2025, 5:55:41 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Neon/torrent_frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/plugins/**/*.{js,ts,mjs}","D:/Neon/torrent_frontend/composables/**/*.{js,ts,mjs}","D:/Neon/torrent_frontend/utils/**/*.{js,ts,mjs}","D:/Neon/torrent_frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Neon/torrent_frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;